version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:0.12.14
    steps:
      - checkout
      - run: terraform init
  plan_apply:
    docker:
      - image: hashicorp/terraform:0.12.14
    steps:
      - checkout
      - run: terraform init
      - run: terraform plan -input=false -out=tfplan
      - run: terraform apply -input=false tfplan
  copy_files:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - aws-s3/sync:
          from: .
          to: s3://something-completely-different
          arguments: |
            --exclude "*" \
            --include "testy*"
          overwrite: true
#      - run: aws s3 sync . s3://something-completely-different --exclude "*" --include "s3*"
workflows:
  version: 2.1
  tf_build:
    jobs:
      - validate
      - plan_apply:
          requires:
            - validate
      - copy_files:
          requires:
            - plan_apply