version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

# variables
# comment to test directory change

base_image: &base_image
  hashicorp/terraform:0.12.14

work_dir: &work_dir
  /tmp/workspace

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *work_dir

# steps

jobs:
  plan_apply:
    <<: *default_config
    steps:
      - checkout
      - run:
          command: |
            cd terraform
            terraform init
            terraform plan -input=false -out=tfplan
            terraform apply -input=false tfplan
  copy_files:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - aws-s3/sync:
          from: "."
          to: "s3://something-completely-different"
          aws-region: aws_region
          arguments: |
            --exclude "*" \
            --include "testy*"

# workflow

workflows:
  version: 2.1
  tf_build:
    jobs:
      - plan_apply
      - copy_files:
          requires:
            - plan_apply